### ISSUE TITLE
duplicate (?) code in drivers\usb\usbmass\usbmass.c:UsbMasspStartDisk()

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#100]
Following code in identified routine seems to have duplicate code, with no comment indicating a need.  (Maybe my eyes are just overlooking a difference?)

Likely benign, but might reduce your load size slightly to eliminate if not needed. :)

    //
    // Send the INQUIRY for page 0 as a friendly "hello!".
    //

    BufferSize = sizeof(SCSI_INQUIRY_PAGE0);
    Status = UsbMasspSendInquiry(Disk, 0, (PVOID)&Page0, &BufferSize);
    if (!KSUCCESS(Status)) {
        goto StartDiskEnd;
    }

    BufferSize = sizeof(SCSI_INQUIRY_PAGE0);
    Status = UsbMasspSendInquiry(Disk, 0, (PVOID)&Page0, &BufferSize);
    if (!KSUCCESS(Status)) {
        goto StartDiskEnd;
    }

    //
    // Get the block device parameters of the disk.
    //

**Comment by evangreen** [comment]
My initial recollection is that this is deliberate, but I can't find any evidence or reasoning for it. Perhaps it was just paranoia paralleling the dual fetch of the USB device descriptor, which everyone seems to do during enumeration. I'm willing to pull out the second inquiry and see what breaks.

Give me a few days to do that internally and I'll update this issue with more info.

**Comment by evangreen** [comment]
This seemed to be okay with all the USB sticks we have here locally, so I've pushed it out. Thanks!
