### ISSUE TITLE
fat12(/fat16) format with root directory entry disliked by windows chkdsk

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#102]
windows (both xp and 7) chkdsk complains about fat12 partition of pc.img with "The \. entry contains a nonvalid link."

(Appears the code in os/lib/fatlib/fat.c:FatFormat() does not produce output that chkdsk is happy with for fat12 and fat16 format.  Leaving out the '.' directory entry seemed enough for fat12, but but even when left out for fat16, get in "Bad links in lost chain at cluster 2 corrected." and ask "Convert lost chains to files (Y/N)?" (which fat12 didn't seem to mention at all.)
)

**Comment by evangreen** [comment]
Ok, I'm working on a change that removes the '.' entry from the root directory. I think the other errors stem from the root directory not being zeroed properly. I always thought a zeroed directory entry signaled the end, but apparently chkdsk keeps scanning until the end of the cluster. I should have that change pushed soon.

**Comment by evangreen** [comment]
I pushed change d46b21d9d4e7d4ec757976cb00b9496efb2beb68 for this issue. If you find a moment, give it a try with the latest and let me know.

**Comment by d-hoke** [comment]
Appears OK Win7/WinXP nightly pc.img dated 03/16/2017.

**Comment by evangreen** [comment]
Excellent. Thanks!
