### ISSUE TITLE
double free attempt appears possible in os/apps/osbase/osbase.c:OsGetCurrentDirectory()

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#103]
(observed from inspection, chasing something else, maybe wrong)
Appears that osbase.c:OsGetCurrentDirectory could attempt a double free if the for loop is exited due to reaching the OS_GET_CURRENT_DIRECTORY_TRY_COUNT limit.

The end of the for loop will free CurrentDirectory, and Status will be STATUS_BUFFER_TOO_SMALL, then the loop is exited (limit reached), and the else clause of the if-else at label GetCurrentDirectoryEnd: will be taken, trying to free the same CurrentDirectory item again.

**Comment by ccstevens** [comment]
I agree with your assessment. We'll get a fix for this. Thanks for finding it!

**Comment by evangreen** [comment]
Chris pushed 2a12b5463c5a1434e3e83ff853503458e4c4d6e8 for this. Please review, and if it passes your inspection then feel free to close.
