### ISSUE TITLE
opkg main gnupg specifies dependency libcgrypt instead of libgcrypt, can't find libcgrypt

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#105]
and doesn't install.

**Comment by d-hoke** [comment]
Even after changing that still issue causing failure to install, missing item libunistring.list,
and
further error regarding gettext wanting to install charset.alias, 'but that package already provided by libiconv'...

**Comment by evangreen** [comment]
The missing lists are weird. Did the disk go through an unclean shutdown or did files in /usr/lib/opkg/info get deleted somehow?

We've finally got our nightly builds posting at http://www.minocacorp.com/download/nightlies/latest-x86 . Those should have fixed the libcgrypt typo. If you download one of the nightly builds, you'll need to point opkg.conf's URL at http://www.minocacorp.com/download/nightlies/latest-x86/0.4/i686/main to get the new packages.

**Comment by d-hoke** [comment]
opkg install gnupg 
installed ok against nightly with pc.img dated 03/16/2017 against (some) state of download/nightlies/latest-x86/0.4/i686/main within the hour before this post.
