### ISSUE TITLE
opkg install gettext fails

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#106]
indicating error(s - twice) 
pkg_get_installed_files: Failed to open //usr/lib/opkg/info/gettext.list: No such file or directory

**Comment by d-hoke** [comment]
Tried this again today with more recent fetches and whatever other changes you've made to packages area, and it succeeded.

Maybe safe to close this.

**Comment by evangreen** [comment]
Awesome, thank you sir! Is issue #105 also solved in the nightlies?
