### ISSUE TITLE
third-party Makefile has typo 'pkgconfig' vs 'pkg-config' on ffmpeg dependcy

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#108]
think it's this revision 'commit 4ecd9029f8d6385d09a683ed1872180814bf2636'

is 
$(call dep,ffmpeg-3.2.1,pkgconfig-0.29.1 libx264-20170102-2245 libvorbis-1.3.5)
should be
$(call dep,ffmpeg-3.2.1,pkg-config-0.29.1 libx264-20170102-2245 libvorbis-1.3.5)

(It may have been in earlier commits.)

**Comment by ccstevens** [comment]
Thanks for reporting this one. I also hit it last week and have a change in our staging repository. We'll get it out in our next third-party update.

**Comment by evangreen** [comment]
This fix is in third-party now.
