### ISSUE TITLE
opkg.conf bad path to Packages.gz?

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#110]
opkg.conf from recently built image (relatively fresh repository fetches) contains
src/gz main http://www.minocacorp.com/packages/0.4/i686/main

and 'opkg update' fails with 
 * opkg_download: Failed to download http://www.minocacorp.com/packages/0.4/i686/main/Packges.gz, wget returned 8

Is(/Are) component(s) missing from the opkg.conf path?

Post in this thread (https://groups.google.com/forum/#!topic/minoca-dev/-k8v5q14gTw) suggests there should perhaps be an addition 'nightlies/latest-x86/' in the path... as in
"http://www.minocacorp.com/download/nightlies/latest-x86/0.4/i686/main/Packages.gz" from that thread.

update: But, changing opkg.conf to that indicated path does not currently work either...
Or, perhaps the path is correct but the path/URL does not yet exist...

**Comment by d-hoke** [comment]
Ok - when I modified it, I missed the additional 'download' segment, and I still had the 'packages' segment.  After I got the path correct, it downloaded ok.

**Comment by evangreen** [comment]
Excellent, glad it's working for you. When we push an official 0.4 release we'll add the matching packages to the official URL location. But until then the nightlies URL will be the way to go.
