### ISSUE TITLE
os/lib/im/elfcomm.c:ImpElfPerformLibraryPathSubstitutions() *Path usage broken in one of else paths

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#112]
Prob: The 'else' path taken when 'ReplacementLength > ReplaceSize' appears to allocate a new buffer, substitute into, then ImFreeMemory(*Path), but a)never replace *Path with the newly allocated buffer 'NewBuffer', and b)possibly attempt to use the *Path buffer (in a subsequent loop iteration) that is no longer valid because it was ImFreeMemory()d.

Prob2: Before any of that is the expression
`        ReplaceStart = (UINTN)CurrentVariable - (UINTN)(*Path);`
which computes ReplaceStart as an offset from start of '*Path', and then later the expression
`        ReplaceSize = (UINTN)CurrentVariable - (UINTN)ReplaceStart;`
which seems to be trying to treat ReplaceStart as a pointer into '*Path', rather than an offset into '*Path'.  Often results in a rather large 'ResultSize' value given values of pointers often active in memory regions, which of course subsequently blows up, also in the same 'else' branch above, trying to use ReplaceStart as an offset.
A correction might be
`        ReplaceSize = (UINTN)CurrentVariable - ((UINTN)*Path + (UINTN)ReplaceStart);`

Additional Observation: 
a)The handling of 'CurrentVariable' seems such that substitutions cannot contain substitutions, at least not that will be found by that routine.  Maybe the syntax/semantics of rpath doesn't support that, my knowledge of them is small.
b)In that problematic else path, the changing of 'CurrentVariable' seems such that searching will start partway into the replacement area, not skipping it entirely - this may not be a problem, but seems one would either want to search the entire replacement (mentioned in (a) above), or skip the entire replacement - not start in the middle of it...?
c)It'd be nice to have those absolute ASSERT()s in that routine gone so they don't trip up debug build users like me. :)

**Comment by d-hoke** [comment]
Well, I now think the 'if' section may be broken as well...

**Comment by ccstevens** [comment]
@d-hoke, working on some fixes for this.

Prob 1: I agree this needs fixing.
Prob 2: Also agree here. Looking at the rest of the code, I think it may be easier to have a ReplaceStart (the pointer) and ReplaceOffset (the offset) to keep things clear. And both seem useful.

Observation A: Going to have to research this one myself.
Observation B: Agreed it needs to be one or the other. Depends on the research.
Observation C: There's a TODO here and the asserts are there because it's not fixed. I'll complete the TODO and remove the asserts.

The "if" case: And are you seeing that the for-loop index is initialized incorrectly? I think it should be:


    for (Index = ReplaceStart + ReplacementLength;
         Index < *PathCapacity - Delta;
         Index += 1) {
   
        CurrentPath[Index] = CurrentPath[Index + Delta];
    }

Thanks for catching the error in ImpElfOpenWithPathList(). I probably would have overlooked that.

**Comment by d-hoke** [comment]
on the for loop - yes, I agree that '+ ReplacementLength' is correct, and the previous '+ ReplaceSize' was/is incorrect.

**Comment by ccstevens** [comment]
Thanks for verifying. That naming was certainly confusing. Switching the original path values to be VariableStart, VariableOffset, VariableLength and keeping the replacement's as Replacement*.

**Comment by ccstevens** [comment]
@d-hoke I ran into a couple of other bugs while sorting out this fix. I'm going to let it run through our next nightly build (Friday 3/24) and then I'll push the changes to GitHub if it looks clean.

**Comment by d-hoke** [comment]
Maybe some of your 'others' were causing the seg violation I still experienced after trying to hack around initial problem... so, sounds good.

**Comment by ccstevens** [comment]
Alright. My fixes are in the latest [nightly build](http://www.minocacorp.com/download/nightlies/2017-03-29) and can be seen in the six changes from [f46ab4a0](https://github.com/minoca/os/commit/f46ab4a067f513547af9274f6cf667da2c7e4941) to [eea60eff](https://github.com/minoca/os/commit/eea60eff4306f4c991c1c4bd94050335629dc7c7).

Let me know if you still run into trouble.
