### ISSUE TITLE
ARMV6 release build error 

### ISSUE THREAD

**Issue by g8kig** [minoca/os#127]
/src/os/kernel/mm/testmm/../x86/mapping.c: In function ‘MmpCreatePageDirectory’:
/src/os/kernel/mm/testmm/../x86/mapping.c:2476:19: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
     KernelIndex = (UINTN)KERNEL_VA_START >> PAGE_DIRECTORY_SHIFT;
                   ^

**Comment by evangreen** [comment]
This is a build regression on non-Windows machines I introduced while starting work on x64 support. The fix is to change that (UINTN) cast to a (ULONG). Let me take a look around and make sure the rest of OS is building, and I'll push a fix.

**Comment by evangreen** [comment]
Pushed 03c0455c31ea2d80d2fc734bea478d1b0d11a2fb. Give the latest master a try.

**Comment by g8kig** [comment]
Build seems good now. Thank you.
