### ISSUE TITLE
PowerPC Port

### ISSUE THREAD

**Issue by mpasteven** [minoca/os#13]
Minoca OS lacks support for PowerPC host CPUs.

With the following repositories, I am investigating porting:

 * <https://github.com/mpasteven/minoca-os>
 * <https://github.com/mpasteven/minoca-third-party-patches>

Note that I have not signed the contributor agreement.

**Comment by evangreen** [comment]
That's awesome. For reference, we wouldn't need the contributor agreement to accept changes into the third-party repository. We only need that for the OS repository.

**Comment by mpasteven** [comment]
After reviewing the code and having made other considerations, I have decided to not pursue this issue at this time.

Also, keeping support for PowerPC would require a maintainer to make sure that the code continues to work when other changes have been made.

**Comment by evangreen** [comment]
No problem. It would definitely be a big undertaking. If you're interested in helping in other, smaller ways, we would of course love the help. Email me for suggestions.

I'm going to go ahead and close this issue.
