### ISSUE TITLE
Need chgrp or equivalent 

### ISSUE THREAD

**Issue by melezhik** [minoca/os#134]
Hi!
Looks like chgrp command does not exist at MinocaOS ... Could you please give me an advice on the equivalent or probably I need to install some package to have this?

Thanks

Alexey

**Comment by evangreen** [comment]
Hi Alexey,
Yep, we should probably add that at some point. In the meantime, can you use `chown :mygroup ...`?

**Comment by melezhik** [comment]
Yeah , thanks, sure will try chown.

**Comment by melezhik** [comment]
`chown :group` works! thanks
