### ISSUE TITLE
mac toolchain problems

### ISSUE THREAD

**Issue by willmafh** [minoca/os#140]
Is there anyone can help?
I am trying to build minoca OS on my Mac and I've spent almost one day, but still failed...
This is my OS version...
<img width="588" alt="screen shot 2018-01-01 at 10 20 45 pm" src="https://user-images.githubusercontent.com/11711429/34468359-14d0b3ce-ef42-11e7-8e86-75cf7e152ddd.png">
The following is the error:
<img width="1440" alt="screen shot 2018-01-01 at 10 21 59 pm" src="https://user-images.githubusercontent.com/11711429/34468403-17839ba8-ef43-11e7-8058-478ab4fe96d8.png">
Please help...

**Comment by evangreen** [comment]
I'm in the process of trying to upgrade my macOS and XCode, but I'm in a location with slow internet access, so I may be a little while. Until I'm able to get my system matching yours, you may be able to make progress by commenting out the offending lines, and setting Result to -1.

**Comment by willmafh** [comment]
Thank you for your response @evangreen ...I just want to make sure that the process I've made was right ... I downloaded the macOS toolchain from the website and then mv x86dbg in learnCCPP, the parent dir of os, then I cd into os to source setenv.sh to let the system find the tools in x86dbg, and then I use make to compile the system ... It compiled very well for a while, then encountered the problem I've showed above ... I used to think that the compiler can't find header files in the toolchain, so I added option -isystem to gcc in minoca.mk and it worked, so it continued to compile, but soon another strange error appeared ... I don't know how to fix it ... Hope this can give you more information ... Waiting for your solution, Thank you ....

**Comment by evangreen** [comment]
I pushed 1bdc1eda4bb2ed19a3f0a2fd53b6919f8ae3c54c, give it a try now.
