### ISSUE TITLE
RPI1 image on website has private IP address in the 'opkg.conf' file.

### ISSUE THREAD

**Issue by g8kig** [minoca/os#142]
The Minoca OS 0.4 RPI1 download image (at https://www.minocacorp.com/download/0.4/Minoca-rpi.zip) has a private IP address in the opkg.conf file in /etc/opkg.
This means that opkg does not work.

The line is:

"src/gz main http://10.0.1.202/packages/0.4/armv6/main"

I think it should be:

"src/gz main http://minocacorp.com/packages/0.4/armv6/main"

**Comment by evangreen** [comment]
Thanks for this, you're right. I can try to get this fixed up in the image on the website.

**Comment by evangreen** [comment]
I've put a new image up at https://www.minocacorp.com/download/0.4/Minoca-rpi-corrected.zip

Would you mind giving this a try? If it works I'll make it the official one.

**Comment by evangreen** [comment]
I made this the official image. Let me know if there are any problems with it.
