### ISSUE TITLE
Chalk missing

### ISSUE THREAD

**Issue by yuppox** [minoca/os#158]
I am getting "chalk: Command not found" during build.

I don't see "chalk" as a requirement for building and I don't know what it is. There are multiple things with this name, so clarification would be helpful.

Thanks.

**Comment by evangreen** [comment]
Chalk is a small interpreted language embedded in Minoca OS. You can find more info about it [here](https://github.com/minoca/os/tree/master/apps/ck). Can you tell me a little more about how you're building? After fixing the issues you pointed out in the other bug, I was able to grab a fresh checkout and build with something like this:
```
evan@westridge:~/src$ wget https://www.minocacorp.com/download/0.4/minoca-tools-linux.tar.gz
evan@westridge:~/src$ tar -xzf ./minoca-tools-linux.tar.gz
evan@westridge:~/src$ mv src/x86dbg/ .
evan@westridge:~/src$ export SRCROOT=$PWD ARCH=x86 DEBUG=dbg
evan@westridge:~/src$ cd os
evan@westridge:~/src/os$ ls
CONTRIBUTING.md  Makefile   apps  build.ck  drivers  include  lib      minoca.mk  new.h      tasks
LICENSE          README.md  boot  docs      images   kernel   menv.ck  new.c      setenv.sh  uefi
evan@westridge:~/src/os$ . setenv.sh
Minoca build environment for x86.
evan@westridge:~/src/os$ echo $PATH
/home/evan/src/x86dbg/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
evan@westridge:~/src/os$ make
```

**Comment by evangreen** [comment]
Assuming this satisfies you're query, let me know if you have more questions or still can't get building.
