### ISSUE TITLE
macos 10.12.1 build, .incbin macro fails to find ckcore.ck 

### ISSUE THREAD

**Issue by seclorum** [minoca/os#26]
As reported in #7, macos builds with latest (10.12.1) toolchain (as of nov. 2) fail to find ckcore.ck when expanding the .incbin macro, thus:

````
Compiling - cdump.c
Assembling - ckcore.S
/Users/seclorum/Documents/minocaOS/src/os/apps/ck/lib/build/../ckcore.S:55:70: error: Could not find incbin file 'ckcore.ck'
.global __binary_ckcore_ck_start; __binary_ckcore_ck_start:; .incbin "ckcore.ck"; .global __binary_ckcore_ck_end; __binary_ckcore_ck_end:
                                                                     ^
make[5]: *** [ckcore.o] Error 1
make[4]: *** [build] Error 2
make[3]: *** [lib] Error 2
make[2]: *** [ck] Error 2
make[1]: *** [apps] Error 2
make: *** [/Users/seclorum/Documents/minocaOS/src/x86dbg/obj/os] Error 2
````

**Comment by ccstevens** [comment]
@seclorum I wasn't able to reproduce this .incbin issue. I'm running macOS 10.12.1 with the xcode 8.1 tools. My steps are below, starting from scratch without previous Minoca macOS toolchains in ~/minocaos/src/x86dbg:

1. mkdir ~/minocaos
2. Download http://www.minocacorp.com/download/minoca-tools-macos.tar.gz into ~/minocaos
3. tar -xzf minoca-tools-macos.tar.gz
4. cd src
5. git clone https://github.com/minoca/os.git
6. export SRCROOT=`pwd`
7. export ARCH=x86
8. export DEBUG=dbg
9. export PATH=$PATH:$SRCROOT/$ARCH$DEBUG/tools/bin
10. cd os
11. make

We'd love to get a repro, so if you can confirm your xcode version and the steps you took to reach the error that'd be awesome!

**Comment by evangreen** [comment]
Hi @seclorum . Chris and I have been tackling this. Just to clarify, can you make sure you've pulled my os changes from last night? You should have commit 5f5e26bf in there.

If it's still not working, then can you remove the @ from what should now be line 519 of minoca.mk, and rebuild, so we can see the command line being run?

Also, so that we can repro it locally, can you tell us where you got the compiler from? Is it the one that comes with XCode or did you install it some other way? We've been using the compiler that seems to magically come with XCode.

**Comment by seclorum** [comment]
Can confirm I am on your latest:
````
* e904499 2016-11-01 | Parallel build fix. (HEAD -> master, origin/master, origin/HEAD) [Evan Green]
* 5f5e26b 2016-11-01 | Fix fseeko64 build break on Apple. [Evan Green]
````

.. still produces this (@ from 519 is removed..)

````
Entering Directory: /Users/seclorum/Documents/minocaOS/src/os/apps/ck/lib/build
Assembling - ckcore.S
gcc  -I /Users/seclorum/Documents/minocaOS/src/os/apps/ck/lib/build/.. -I  /Users/seclorum/Documents/minocaOS/src/os/include -DDEBUG=1  -Wa,-I/Users/seclorum/Documents/minocaOS/src/os/apps/ck/lib/build -c -o ckcore.o /Users/seclorum/Documents/minocaOS/src/os/apps/ck/lib/build/../ckcore.S
/Users/seclorum/Documents/minocaOS/src/os/apps/ck/lib/build/../ckcore.S:55:70: error: Could not find incbin file 'ckcore.ck'
.global __binary_ckcore_ck_start; __binary_ckcore_ck_start:; .incbin "ckcore.ck"; .global __binary_ckcore_ck_end; __binary_ckcore_ck_end:
                                                                     ^
make[5]: *** [ckcore.o] Error 1
make[4]: *** [build] Error 2
make[3]: *** [lib] Error 2
make[2]: *** [ck] Error 2
make[1]: *** [apps] Error 2
make: *** [/Users/seclorum/Documents/minocaOS/src/x86dbg/obj/os] Error 2
````

**Comment by seclorum** [comment]
````
$ ../x86dbg/tools/bin/i686-pc-minoca-gcc  -I/Users/j/Documents/minocaOS/src/os/apps/ck/lib/build/.. -I  /Users/j/Documents/minocaOS/src/os/include -DDEBUG=1  -Wa,-I/Users/j/Documents/minocaOS/src/os/apps/ck/lib/build -c -o ckcore.o /Users/j/Documents/minocaOS/src/os/apps/ck/lib/build/../ckcore.S
````

Okay, this seems to be the problem: system gcc being used, versus the toolchain.   Somehow, chalk is not set up to use the provided toolchain and is getting system gcc instead ..

So, I imagine that you Linux users are generating x86 .o's with your local compilers just fine, whereas in the Darwin case, gcc "out of the box" doesn't like those spaces in the -I .. 

````
 seclorum@github:~/Documents/minocaOS/src/os {(master)}
$ ls -l `which gcc`
lrwxr-xr-x  1 seclorumj  admin  7 Jan 17  2015 /usr/local/bin/gcc -> gcc-4.9

 seclorum@github:~/Documents/minocaOS/src/os {(master)}
 $ ../x86dbg/tools/bin/i686-pc-minoca-gcc  --version
i686-pc-minoca-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 seclorum@github:~/Documents/minocaOS/src/os {(master)}
$ gcc --version
gcc (Homebrew gcc49 4.9.3) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

**Comment by evangreen** [comment]
Well ckcore.ck is really a source. Chalk builds for both the build machine and for Minoca. We're having trouble creating the build machine version (which is why it's using the system GCC). 

The current directory when the file is compiled is going to be src/x86dbg/obj/os/apps/ck/lib/build . For some reason my version of the system GCC must be passing an include path to the assembler that includes the directory the source file is in, while your version seems unwilling to search there. Let's try adding that specific path directly.

Can you try adding this line to apps/ck/lib/build/Makefile, right before "include $(SRCROOT)/os/minoca.mk":

EXTRA_ASFLAGS += -Wa,-I$(SRCDIR)/..

**Comment by evangreen** [comment]
Ah okay, Chris clued me in to the key output in your last message, which was Homebrew.

I was able to get Homebrew+GCC-6 installed on my macbook and reproduce the issue. The fix I posted above works, so I committed it as 053faaa. Grab the latest and you should be good here.

Sorry for all the build trouble. Now to see if it runs :)

**Comment by aequitas** [comment]
@evangreen I pulled down the latests changes and it seems to solve the problem for ckcore. 

However I run into a new issue: https://github.com/minoca/os/issues/29

**Comment by seclorum** [comment]
ckcore issue is fixed for me, thanks for the work on the build issue guys, looking forward to digging in further ..
