### ISSUE TITLE
Building for Transmeta Crusoe (or simply i586 in general)?

### ISSUE THREAD

**Issue by drawkula** [minoca/os#28]
What is neccessary to build Minoca for a Transmeta Crusoe based system?

Can I just try the x86q port?

I've got some Fujitsu Siemens Futro S220 thin clients idling and collecting dust which previously were used as x86-OpenWrt guinea pigs. Typically they have 128M RAM and a filesystem on a 128M CF but I can upgrade some of them to 512M RAM (their maximum), 512M CF card (or more but not at hand) and if that's not enough they can boot or run from USB (tested with i586ish Linux) or I can add a harddisk.

**Comment by evangreen** [comment]
Wow, I'd never heard of this machine before. Yes, the x86q port should build appropriately for an i586 machine. It's worth a try. The only things that might get sticky are that we need an APIC, and appropriate ACPI tables (FADT and MADT mostly). In my extremely brief googling of this device I also noticed what looks like a patch to upgrade the machine to i686:

http://www.techeye.net/software/patch-turns-transmeta-crusoe-into-a-full-i686

**Comment by drawkula** [comment]
If I understand the article correctly, that trick is catching the wrong opcode (via exception or similar digital magic) and triggers a routine in the kernel to emulate the correct behaviour.

For Minoca this means, it would need to have this routine in the kernel too...

That's beyond my knowledge (as of today) and probably not worth the effort. And for porting the x86q stuff over to the Crusoe I definitely know far too less about ACPI and friends.

I will extend my RasPI fleet to dive into Minoca and will give the Crusoes other stuff to play with... ;-)

**Comment by drawkula** [comment]
I tried to add a "port" for an architecture like x86 but using an i586 toolchain.

So far the result still doesn't like my Crusoe systems, but it happily runs in Qemu with `-cpu pentium` and accepts i586 packages from Minoca's packages server.

I called the ARCH `x86v` with 'V' like roman five to hint to pentium...

Probably I have totally screwed the Windows specific parts of the build by trying to guess what's expected in there, the current state only was tested on Debian-8.6/AMD64.

The diffs for "os" and "third party": [x86v.diffs.zip](https://github.com/minoca/os/files/653747/x86v.diffs.zip)

**Comment by ccstevens** [comment]
I glanced at the diffs. Correct me if I'm wrong, but it looks like you derived 'x86v' by looking at how 'x86q' works. Is there any difference between the two other than the 'os/images/Makefile' using '-ql pc' rather than '-ql galileo'?

While this is a good start, the easier route would probably be to extend 'x86q' to include a '-ql pc' image. Or just rename 'x86q' to your more generic 'x86v' and then add the '-ql pc' image. There is no real reason to have two build variants that target 'i586'.

That said, the boot is probably getting tripped up by what Evan pointed out earlier. The Crusoe does not have an I/O APIC, which Minoca requires. You'd have to support for the Cursoe's interrupt controller in 'os/kernel/hl/x86'. And then you'd have to check to see what ACPI tables the firmware is exposing.

**Comment by drawkula** [comment]
> While this is a good start, the easier route would probably be to extend 'x86q' to include a '-ql pc' image.

I just didn't dare to mix up 'x86q' directly and I wasn't expecting that adding the PC image would be all that needs to be done.

> That said, the boot is probably getting tripped up by what Evan pointed out earlier. The Crusoe does not have an I/O APIC, which Minoca requires.

I'm not sure about Crusoe still being my target but I think, having a VM springboard for other 'i586' based systems is a good thing.

> Or just rename 'x86q' to your more generic 'x86v' and then add the '-ql pc' image. There is no real reason to have two build variants that target 'i586'.

Ok.
So can you please add the PC image to the "Quark port"?

The naming question is a different story.

Why is the 'i686' port named 'x86'? That gives the illusion that it might run on all 86ers which definitely is not the case. It wants at least 'i686' aka Pentium-Pro.

Same with 'x86q' requiring at least 'i586' instead of some 86er.

So if both ports could be renamed to 'i686' and 'i586' it'd give a stronger connection between names and requirements and as with 'armv6' and 'armv7' the name directly would map to the arch part of the packages' names ('minoca-$ARCH').

Some IFs less in install scripts... I like that idea...

But probably 'x86' and 'x86q' already are burned in too many brains and scripts. That change would not be as cheap as just adding the PC image... :-(

Maybe add `i?86` names as aliases now and fade out the x-names slowly?
