### ISSUE TITLE
There is a stray copy of xcopy.exe in the Minoca gitlab tools respository.

### ISSUE THREAD

**Issue by g8kig** [minoca/os#32]
This is a direct link: [https://gitlab.com/minoca/tools/blob/master/win32/bin/xcopy.exe
](https://gitlab.com/minoca/tools/blob/master/win32/bin/xcopy.exe
)
For me this causes the Minoca thirdparty build on Windows to fail because it fails to execute with an "entry point not found error".
Removing this file results in a successful build of the third party tools.
I suggest that it is removed from the repository.

**Comment by evangreen** [comment]
Fixed with change 5e9eae83 in tools. Thanks!
