### ISSUE TITLE
Running in VirtualBox with vmdk

### ISSUE THREAD

**Issue by KawaniwaHikaru** [minoca/os#33]
Hi, want to share my finding with the VirtualBox here

I have tried Evan's method of manually creating the vmdk file to wrap the pc.img, however I get a miss matched uuid stored in the media registry. To fix this I had to copy out the UUID of the ones in the media registry and replace it 
``ddb.uuid.image="69a7ab8a-ac25-42c6-b673-6c6ca1a36594"``

but an easier approach is to have the pc.img and run
``VBoxManage internalcommands createrawvmdk -filename pc.vmdk -rawdisk pc.img``
which will generate the pc.vmdk for you, now you can just mount the vmdk as is.

hope this helps anyone who may have issues.

**Comment by evangreen** [comment]
Thanks Brian. Do you mind if I add that command to docs/virtualbox.txt?

**Comment by KawaniwaHikaru** [comment]
not a problem, or I can modify and create a pull request

**Comment by evangreen** [comment]
Sure, go ahead. I think my manually created vmdk would have worked without headache if I had removed the last 4 ddb.uuid.* properties. So I was planning on yanking those 4 lines and then adding your command line as an alternative suggestion.
