### ISSUE TITLE
Include opkg on the generated OS image

### ISSUE THREAD

**Issue by vascocosta** [minoca/os#40]
I'm using the tools repo to set up a build environment on Windows. I can easily build the needed third-party tools and the kernel, as well as individual packages by going to the src/third-party/build/package_name dir and issuing make there.

Is there some make target or other obvious way to include the opkg binary on the generated OS image, so that I can easily install other packages when testing the image on Qemu with run dx?

If this makes any sense, would it also make sense to include the ipkg files of the third-party packages on the disk image of the OS as well (a quick way to have a local repo for opkg inside the image itself)?

**Comment by drawkula** [comment]
Look at [issue 24/258632478](https://github.com/minoca/os/issues/24#issuecomment-258267150) how to include unpacked third-party builds in the image.

You soon will need a bigger image size: [issue 24/258267150](https://github.com/minoca/os/issues/24#issuecomment-258267150)

[issue 24/258267150](https://github.com/minoca/os/issues/24#issuecomment-258267150) plays with copying the whole `bin/packages` directory into the `bin/apps` directory which will make it land in `/packages` in the generated image.

Still an ugly hack but helps to get started now/somehow.

My `opkg` seems to ignore it's config file `/etc/opkg/opkg.conf` but behaves correctly when called with explicit definition of the config file location: `opkg -f /etc/opkg/opkg.conf [otherOptions] [Args]`

**Comment by evangreen** [comment]
I think we should create a make target in third-party that would build opkg+dependencies (and maybe dropbear or openssh?), and then run opkg-extract-data to install those packages into x86dbg/bin/apps. 

The new make target could depend on the tools that it needs, and then call a new script in third-party/build with the packages as its arguments to do the extraction.

Anybody interested in tackling that?

**Comment by melezhik** [comment]
@evangreen +1 for this. and yes openssh will  be useful too

**Comment by vascocosta** [comment]
@evangreen Just to let you know that I am currently tackling this as per your makefile/script suggestion. I'll let you know when I'm done.

**Comment by drawkula** [comment]
Check `opkg-utils/opkg-extract-file` ... being "cross running" it can't run package pre/post install scripts. Adding complex packages this way probably is not a good idea.

`gzip`, `opgk`, `tar`, `wget` and their dependencies probably is the barest minimum to install. Every other stuff can be included as packages or even got from elsewhere (USB, net, ...).

An editor may(!) be nice too but including `nano-*.ipk` as is or other editors sure would be good enough.

`openssh` sure is a member of the "too complex" group.

Are you planning to build the dependencies list from `bin/Packages` previously built by `opkg-make-index`?

**Comment by evangreen** [comment]
I just pushed some changes to third-party to do this. You can now run "make install-minimal" in third-party, which will build+extract opkg and Dropbear, and then manually patch up the remaining configuration needed by Dropbear. You'll need to pull the latest from "os" this evening as well.

**Comment by melezhik** [comment]
Hi Evan! Sure, will take a look at the things you say.

Meanwhile you may try to run it  ( and let me know if any other issues you face ... ) so we don't wait each other ))) as we are in quite different time zones and out interaction sometimes gets delayed due that ....

**Comment by vascocosta** [comment]
This a great and useful new feature. I tried implementing this earlier, but then stalled for some reason related to make. I'll take the chance to see how you tackled it.

I'm closing this one.
