### ISSUE TITLE
hp pro 640 2g green screen...

### ISSUE THREAD

**Issue by Stepanov-Sergey** [minoca/os#43]
(dd-ing to usb-stick)

**Comment by evangreen** [comment]
@Stepanov-Sergey Can you be more specific? Completely blank green screen, or uptime printed but not ticking, or uptime ticking? Are you using an image you created from source or one you pulled off a website?

If you're feeling up to it, a kernel debugger would be immensely helpful. You'd need an FTDI USB to serial cable plugged in through a hub on your laptop. There's some more info at http://www.minocacorp.com/documentation/developers/debug/docs/platform/

**Comment by Stepanov-Sergey** [comment]
...at this point I have only serial port device pl2303 (ID067b:2303)
and lenovo z575  displays blank green screen too.. 
i used this image http://www.minocacorp.com/download/Minoca-pc-1375.zip

**Comment by evangreen** [comment]
We may be able to at some point, but it won't be immediate. Your best bet would be an FTDI USB to serial cable, which aren't too expensive.

**Comment by evangreen** [comment]
Give the new images a try here, too. Did you manage to get ahold of an FTDI serial port? They're pretty cheap on eBay!
