### ISSUE TITLE
Chalk

### ISSUE THREAD

**Issue by severak** [minoca/os#5]
Hi,
it seems you are using some language called "Chalk" throughout the project.

Is it something that existed before Minoca or it was developed for this project only?

**Comment by mnp** [comment]
I've managed to figure out this much :-) from chalk.c

`#define CHALK_USAGE                                                            \
    "usage: chalk [options] [file] [arguments...]\n"                           \
    "Chalk is a nifty scripting language. It's designed to be intuitive, \n"   \
    "small, and easily embeddable. Options are:\n"                             \
    "  --debug-gc -- Stress the garbage collector.\n"                          \
    "  --debug-compiler -- Print the compiled bytecode.\n"                     \
    "  --help -- Show this help text and exit.\n"                              \
    "  --version -- Print the application version information and exit.\n"
`

**Comment by evangreen** [comment]
Chalk is a new scripting language that I wrote for Minoca OS. Like the comment above says, I wanted something that was small, embeddable, had a familiar syntax. I was also designing it with the eye of potentially taking it into kernel mode some day, though as of today I don't have a need for that. What I did need is a basic description language for the msetup recipes and upcoming build system.

I realize there are other scripting languages that fit my criteria, but in the interest of not dragging in unknown dependencies I decided to just create a small one on my own.

I'll mention here that Chalk is actually in transition right now, as it took me two attempts to write it. The files in apps/lib/chalk are the old chalk interpreter which will be deleted soon. The Chalk interpreter that you found in apps/ck is the new interpreter going forward.

The .ck files sprinkled around everywhere are part of a build engine I'm creating with Chalk called mingen. The goal is to switch from Makefiles to Ninja, with mingen being the front end that creates Ninja files.

I just finished porting msetup to use the new Chalk interpreter, but mingen and all the .ck files are still on the old interpreter, which has incompatible syntax (mostly the fact that in the new interpreter you need to declare variables with var, where you could just start using them in the old interpreter).

So there's the rundown on Chalk.

**Comment by evangreen** [comment]
I'm going to to ahead and close this one now. Feel free to email me if you've got more questions.
