### ISSUE TITLE
Add asynchronous IO to wishlist

### ISSUE THREAD

**Issue by Varriount** [minoca/os#50]
I don't know if any thought has been given to any unique-to-minoca user mode api's, but a proper asynchronous IO mechanism would be nice (preferably using a proactor pattern rather than a polling pattern) .

**Comment by evangreen** [comment]
Agreed, this would be good to have.

**Comment by evangreen** [comment]
I've added this to the WISHLIST.md file. It should get pushed out to Github in the next few days. Not very satisfying, as it would be nice to actually build async I/O, but at least it's tracked.
