### ISSUE TITLE
Include win32 binary of pkg-config on the tools repo

### ISSUE THREAD

**Issue by vascocosta** [minoca/os#51]
I've been trying to port new packages to Minoca OS using the Windows cross-compiling environment and some of those packages require pkg-config.

I simply grabbed a binary here: http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip and moved on with configuration/compilation.

Since this is so ubiquitous, would it be possible to include it on the tools repo for Windows?

**Comment by vascocosta** [comment]
Those SOMEPKG_CFLAGS/SOMEPKG_LIBS are quite a nice workaround for pkg-config, however setting GLIB_CFLAGS/GLIB_LIBS when trying to build irssi doesn't seem to work and configure bails out. Apparently irssi's configure script only cares for SSL_* ones and always calls pkg-config for glib.

Your suggestion to convert pkg-build to a tool seems quite logical to me. I'm not sure I'll be able to successfully build it that way though. Nevertheless I'll get my hands dirty for the sake of learning more if nothing else.

Meanwhile, if you find a quicker way which allows the irssi package I submitted to build without a pkg-config.exe on Windows, please let me know.

**Comment by evangreen** [comment]
I played with it a little last night and managed to get pkg-config building as a tool on windows. I'll attach my third-party/build/pkg-config-0.29.1 directory here for you. The diff has changed, so make sure to do a make clean in pkg-config first. But I was unable to use that new pkg-config to build irssi. I didn't try very hard though, as I was hungry. I'll try again later, or let me know if you find the trick first. Perhaps pkg-config didn't build right.
[pkg-config-0.29.1.zip](https://github.com/minoca/os/files/592668/pkg-config-0.29.1.zip)

I'll also need to try my pkg-config changes on macOS and Linux.

**Comment by vascocosta** [comment]
Good job.

I was able to build pkg-config from your new recipe, but I don't see any pkg-config.exe being generated, only the Minoca ELF at x86dbg\obj\third-party\pkg-config-0.29.1.build\build.out\usr\bin.

Shouldn't there also be a x86dbg\obj\third-party\pkg-config-0.29.1.**tool** where Windows executables are staged?

As soon as you can generate a pkg-config.exe, adding "export PKG_CONFIG=path_to_pkg.config.exe" to irssi's build.sh script near PKG_CONFIG_PATH=$DEPENDROOT/usr/lib/pkgconfig/ will surely work. I managed to build it before this way, using a win32 pkg-config binary I downloaded from freedesktop.

**Comment by evangreen** [comment]
Yes, there should be a pkg-config-0.29.1.tool directory. Are you running "make tools" from within third-party/build/pkg-config-0.29.1?

**Comment by vascocosta** [comment]
My bad... Temporary brain fade, sorry. :)

**Comment by vascocosta** [comment]
I just successfully compiled irssi, this time using your pkg-config tool built for Windows!

I simply added: 

`if test "x$BUILD_OS" = "xwin32"; then
    export PKG_CONFIG="$SRCROOT/$ARCH$VARIANT$DEBUG/tools/bin/pkg-config.exe"
fi`

Here's the updated build folder:

http://hydrogen.geekzone.tk:23720/minoca/packages/0.3/i686/main/irssi-0.8.20.zip

Let me know if you still have any issues.

**Comment by evangreen** [comment]
Okay, with a little tweaking I was able to get this to build with pkg-config built as tools. I've pushed those changes to third-party. Thanks for putting irssi together, I'm excited to try it out.

Closing this now.

**Comment by vascocosta** [comment]
Thanks @evangreen, good job again, fixing this issue and helping out with irssi.

I had missed the extra dependencies you added probably because I did a "make" inside third-party early on, so I already had ALL packages built and irssi was therefore building successfully too. This way I was wrongly assuming all the dependencies were met when they weren't. Something to take into consideration now that I'll create more packages.
