### ISSUE TITLE
networking for dummies (where's ifconfig?)

### ISSUE THREAD

**Issue by donbright** [minoca/os#59]
I booted up the pc.img inside of virt-manager / QEMU on ubuntu but i cannot for the life of me figure out how to make opkg update work per the tutorial guide on the website. 

My qemu installation guest apparently has no outbound networking connection, since opkg update reports an error of  'wget returned 4'. I also tried 'telnet' for example 'telnet google.com 80' or 'telnet 8.8.8.8 80' which normally is an easy way to test basic networking functionality. These also did not work.

My normal procedure to diagnose network problems is to run something like 'ifconfig', but i cannot find anything that seems equivalent here. I also could not find any documentation regarding network diagnostics or tools. 

I tried to use 'netcon' but it wants a 'device name'. I looked under '/dev' but did not see anything that looked like a network device. 

What can i do? 

Thanks for any help.

**Comment by drawkula** [comment]
@donbright ... I don't know or use `virt-manager`. My `qemu` launch script looks like:
```
(yeti@kumari:11)/wrk/minoca/qemu$ cat run
#!/bin/sh
exec qemu-system-x86_64 \
        -enable-kvm \
        -smp 2 \
        -m 1024 \
        -net nic,model=i82559er,macaddr=fe:fd:0a:00:02:0e \
        -net user,hostfwd=tcp::22222-:22 \
        "$@" \
        &
```
I did not include an option for the drive(s) because I often use different images or more of them in different order. For one disk image it looks like `./run -drive file=system.32G.qcow2`.

Use `-drive format=raw,pc.img` for raw images like the ones from building Minoca OS.

The `-net` options define which network card `qemu` shall emulate and the `hostfwd` makes ssh-ing into the VM possible if OpenSSH is correctly installed inside the VM.

It works. Instead of a screenshot:
```
~# netcon     
Minoca Network Configuration:

Network Device 0x19:
        Physical Address: FE:FD:0A:00:02:0E
        IPv4 Address: 10.0.2.15
        Subnet Mask: 255.255.255.0
        Gateway: 10.0.2.2


~# opkg update
Downloading http://www.minocacorp.com/packages/0.3/i686/main/Packages.gz.
Inflating http://www.minocacorp.com/packages/0.3/i686/main/Packages.gz.
Updated list of available packages in /var/opkg-lists/main.
~# _
```

**Comment by donbright** [comment]
thanks. that was helpful.

in virt-manager basically the first step is to say 'use an exisiting image' then select pc.img

now using your info, what you need to do is go into the 'info' for the VM and change the network device from rtl8139 to n1000

now, when i run 'netcon' i see a useful result, and opkg update works fine!

my only last question would be this.... is there a way to get a 'list of devices' from the kernel so that i can figure out whether or not it has detected a network device?

thanks for the help

**Comment by ccstevens** [comment]
@donbright There isn't an application that spits out a 'list of [all] devices' from the kernel. `netcon` is there to list the network devices. If you run it without arguments and it just prints "Minoca Network Configuration:", then there are no network devices present. I now realize that's horrendous UI and made you think you needed to supply a device ID. I'm putting in a fix to print "No network devices detected." instead.

Also, we do have an rtl8139 driver. I'll have to see why we didn't detect that device with virt-manager / QEMU.

**Comment by ccstevens** [comment]
Figured out the issue in the Minoca rtl81xx.drv. It was timing out during PHY initialization while waiting for a reset bit to clear in a register. The RealTek RTL8139C+ specification states that bit 15 of register 0x62 is self-clearing, but QEMU does not clear the bit (confirmed via source inspection). I've created a fix and it will be pushed to GitHub within the next week.

**Comment by donbright** [comment]
wow thanks!!
