### ISSUE TITLE
Please please please consider GPL-3+

### ISSUE THREAD

**Issue by irl** [minoca/os#6]
If GNU release a later version, then GPL-3 code will probably be incompatible with GPL-4.

Rationale from http://opensource.stackexchange.com/questions/1777/why-is-gplv2-incompatible-with-gplv3:

> Both the GPLv2 and the GPLv3 have clauses that
> 
> >    Require the combined product to adhere to the license terms of the license of the GPL licensed component.
> 
> >    Require that no additional restrictions may be placed on the combined work:
> 
> from clause 6 of the GPLv2:
> 
> >    Each time you redistribute the Program (or any work based on the Program), the recipient automatically receives a license from the original licensor to copy, distribute or modify the Program subject to these terms and conditions. (Part 1) You may not impose any further restrictions on the recipients' exercise of the rights granted herein. (Part 2)
> 
> The GPLv3 has additional restrictions over the GPLv2, specifically, a patent grant and anti-tivoisation provisions, so 1 and 2 can't hold simultaneously.
> 
> To prevent this issue, the Free Software Foundation advises people who want to license their work under the GPL to use the following phrasing:
> 
>     You can redistribute it and/or modify [the work] under the terms of the GNU General Public License as published by the Free Software Foundation, either version [x] of the License, or (at your option) any later version.
> 
> That way, you release your work under multiple licenses; the one you name explicitly, and any possible future version of the GPL. This makes the resuser free to use the software under any future version of the GPL, and this license incompatibility becomes a non-issue.

**Comment by evangreen** [comment]
Given how different GPLv3 was from GPLv2, and given that I don't know what the terms of a GPLv4 might be, I'm not sure I'm comfortable with the automatic upgrade. If/when GPLv4 comes out we can evaluate it and see if it makes sense for us.

**Comment by irl** [comment]
The problem with that is that you then require copyright assignment, which means that if patches are written by third-parties who do not give copyright assignment and you choose to later change the license, you can't without getting the permission of people who may not be contactable.

One potentially important factor here is that any code that is written for the Linux kernel would need to be explicitly dual-licensed as the Linux kernel uses GPL-2. Integrating BSD or MIT licensed code is easier as you just maintain dual license for the bits you've integrated.

I honestly believe that the only effective way to use GPL that doesn't shoot you in the foot later is to use "version 2, or at your option any later version".

**Comment by Conan-Kudo** [comment]
@evangreen Declaring something as "GPLv3+" (or formally "version 3, or at your option any later version") means not that it's an automatic upgrade, but that it's actually possible for people to use it under new terms easily.

**Comment by evangreen** [comment]
Thanks for the feedback. I think for now I'm still going to hold on my position. We can revisit this again as the project matures.
