### ISSUE TITLE
No caretaker for old PTYs...

### ISSUE THREAD

**Issue by drawkula** [minoca/os#63]
```
(root@minoca:pty6)/src/os# ls -l /dev
total 64
crw-------  1 root root  0 Jan 01  2001 console
crwxrwxrwx  1 root root  0 Jan 01  2001 full
crwxrwxrwx  1 root root  0 Jan 01  2001 null
-rw-r--r--  1 root root  0 Nov 22 20:18 pty0
-rw-r--r--  1 root root  0 Nov 22 20:18 pty0m
-rw-r--r--  1 root root  0 Nov 23 13:15 pty1
-rw-r--r--  1 root root  0 Nov 23 13:15 pty1m
-rw-r--r--  1 root root  0 Nov 23 15:42 pty2
-rw-r--r--  1 root root  0 Nov 23 15:42 pty2m
-rw-r--r--  1 root root  0 Nov 23 15:44 pty3
-rw-r--r--  1 root root  0 Nov 23 15:44 pty3m
-rw-r--r--  1 root root  0 Nov 23 15:56 pty4
-rw-r--r--  1 root root  0 Nov 23 15:56 pty4m
-rw-r--r--  1 root root  0 Nov 23 16:06 pty5
-rw-r--r--  1 root root  0 Nov 23 16:06 pty5m
crw--w----  1 root  tty  0 Nov 23 16:13 pty6
crw-r--r--  1 root root  0 Nov 23 16:13 pty6m
dr-xr-xr-x  1 root root  0 Jan 01  2001 Terminal
crwxrwxrwx  1 root root  0 Jan 01  2001 tty
crwxrwxrwx  1 root root  0 Jan 01  2001 urandom
dr-xr-xr-x  1 root root  0 Jan 01  2001 Volume
crwxrwxrwx  1 root root  0 Jan 01  2001 zero
```
...probably some cleanup action is missing.

**Comment by evangreen** [comment]
This is weird, these should clean themselves up when the last process using them is closed. Did you just log into new openssh sessions and close the sessions to create these?

**Comment by drawkula** [comment]
Perhaps this is a Qemu thingy...

Minoca OS in real hardware (PI1 + PI2) still is on my acceleratingly expanding (dark energy inside!) to do list... perhaps this behaves better on real hardware... but then... what about power loss? Shouldn't that be equal to just closing Qemu while Minoca OS is idling?

I seem to get a new PTY after each brute force switch off while a SSH connection is active.
```
(yeti@kumari:14)/wrk/minoca/qemu$ ./run -drive file=system.32G.qcow2
(yeti@kumari:14)/wrk/minoca/qemu$ ssh -p22222 yeti@localhost 
yeti@localhost's password: 
(yeti@minoca:pty8)~$ Connection to localhost closed by remote host.
```
I closed Qemu. The message above seems to come from the `ssh` client on Debian.
Restart Qemu with the same Minoca disk image...
```
(yeti@kumari:14)/wrk/minoca/qemu$ ./run -drive file=system.32G.qcow2
(yeti@kumari:14)/wrk/minoca/qemu$ ssh -p22222 yeti@localhost 
yeti@localhost's password:
(yeti@minoca:pty9)~$ exit
logout
Connection to localhost closed.
(yeti@kumari:14)/wrk/minoca/qemu$ ssh -p22222 yeti@localhost 
yeti@localhost's password: 
(yeti@minoca:pty9)~$ █
```
Exiting only the `ssh` session and reconnecting reuses the PTY...

Stale PTY entries seem to be produced by "brutal SHOTdowns"...

**Comment by evangreen** [comment]
Oh I see. We create empty files to back the special terminal files that get created. Those empty files are written to disk, so when you surprise power off the machine and reboot, they appear as normal empty files. Upon coming back there's not much we can do to distinguish between those empty files and normal real empty files (and you can see they've lost their special status). They are however safe to delete. So I suppose this is "expected behavior".

**Comment by drawkula** [comment]
Adding PTY cleanup somewhere in the init scripts should be ok then... perhaps side by side to <strike>cleaning</strike> smashing and recreating `/tmp` in `init.sh`?

**Comment by evangreen** [comment]
Yes that would work.

**Comment by evangreen** [comment]
@drawkula Do you want to take a crack at this? Otherwise I'll probably close it as "not worth worrying about right now".

**Comment by drawkula** [comment]
After looking a bit longer at it I think `init.sh` should be the bare minimum to get the `chroot` up.
E.g. creating/cleaning `/tmp` and `/dev/pty*` stuff and the new `ssh`-hacks should be in the `chroot`.

Btw.: Shouldn't `/tmp` be mode `1777`?
