### ISSUE TITLE
pkg-config compilation error - pkg-config.exe’: No such file or directory

### ISSUE THREAD

**Issue by melezhik** [minoca/os#66]
Hi I am tring to build third party package nano.

1. set evnvars
2. cd $SRCROOT/third-party
3. make

last N lines of make log:

```
Making install in .
make[3]: Entering directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool'
make[4]: Entering directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool'
 /bin/mkdir -p '/home/vagrant/minoca/x86dbg/tools//share/doc/pkg-config'
 /bin/mkdir -p '/home/vagrant/minoca/x86dbg/tools//share/man/man1'
 /bin/mkdir -p '/home/vagrant/minoca/x86dbg/tools//share/aclocal'
 /bin/mkdir -p '/home/vagrant/minoca/x86dbg/tools//bin'
 /usr/bin/install -c -m 644 pkg.m4 '/home/vagrant/minoca/x86dbg/tools//share/aclocal'
 /usr/bin/install -c -m 644 /home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.src/pkg-config-guide.html '/home/vagrant/minoca/x86dbg/tools//share/doc/pkg-config'
 /usr/bin/install -c -m 644 /home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.src/pkg-config.1 '/home/vagrant/minoca/x86dbg/tools//share/man/man1'
  /bin/sh ./libtool   --mode=install /usr/bin/install -c pkg-config '/home/vagrant/minoca/x86dbg/tools//bin'
libtool: install: /usr/bin/install -c pkg-config /home/vagrant/minoca/x86dbg/tools//bin/pkg-config
make  install-exec-hook
make[5]: Entering directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool'
cd /home/vagrant/minoca/x86dbg/tools//bin && ln -sf pkg-config x86_64-unknown-linux-gnu-pkg-config
make[5]: Leaving directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool'
make[4]: Leaving directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool'
make[3]: Leaving directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool'
Making install in check
make[3]: Entering directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool/check'
make[4]: Entering directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool/check'
make[4]: Nothing to be done for 'install-exec-am'.
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool/check'
make[3]: Leaving directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool/check'
make[2]: Leaving directory '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool'
cp: cannot stat ‘/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool/.libs/pkg-config.exe’: No such file or directory
Makefile:70: recipe for target 'tools' failed
make[1]: *** [tools] Error 1
make[1]: Leaving directory '/home/vagrant/minoca/third-party/build/pkg-config-0.29.1'
Makefile:233: recipe for target '/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool/build.stamp' failed
make: *** [/home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool/build.stamp] Error 2

```

my environment:

```

vagrant@Debian-jessie-amd64-netboot:~/minoca/third-party$ echo $PATH
/home/vagrant/minoca/src/x86dbg/tools/bin/:/home/vagrant/minoca/x86dbg/tools/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

vagrant@Debian-jessie-amd64-netboot:~/minoca/third-party$ echo $DEBUG
dbg
vagrant@Debian-jessie-amd64-netboot:~/minoca/third-party$ echo $SRCROOT
/home/vagrant/minoca

vagrant@Debian-jessie-amd64-netboot:~/minoca/third-party$ echo $ARCH
x86

vagrant@Debian-jessie-amd64-netboot:~/minoca/third-party$ pwd
/home/vagrant/minoca/third-party

```

**Comment by melezhik** [comment]
my makefile has minor adjustments:

```

vagrant@Debian-jessie-amd64-netboot:~/minoca/third-party$ git diff
diff --git a/Makefile b/Makefile
index 95e8f8c..87c1d13 100644
--- a/Makefile
+++ b/Makefile
@@ -169,6 +169,7 @@ APPS += flex-2.5.39             \

 endif

+APPS = nano-2.2.6

 PACKAGES := $(ALL_TOOLS) $(APPS)
```

**Comment by vascocosta** [comment]
Recently pkg-config was added as a tool, maybe you didn't build it yet? Try make all-tools again before trying to build nano:

`cd $SRCROOT/third-party
make all-tools
cd build/nano-2.2.6
make`

**Comment by melezhik** [comment]
Yeah, but I thought that "make all-tools" is invoked by "make"? Also the issue is not with "nano make" itself , but with "make for the root directory - third-party/" ...

**Comment by melezhik** [comment]
And it looks like that make for pkg-config indeed gets called, see previous log , but this make fails ...

**Comment by vascocosta** [comment]
If you invoke make without any target inside $SRCROOT/third-party or $SRCROOT/third-party/pkg-config-0.29.1 it defaults to the "all" target, which builds pkg-config as a normal package and not a tool.

You should always run `make tools` and `make all-tools` at least once before running `make` alone.

**Comment by vascocosta** [comment]
But then again I see /home/vagrant/minoca/x86dbg/obj/third-party/pkg-config-0.29.1.tool in your log, so it was indeed built as a tool. I'm not sure what's the problem.

**Comment by vascocosta** [comment]
I think the problem arises from pkg-config's build.sh:

```
  build-tools)
    make $PARALLEL_MAKE
    make $PARALLEL_MAKE install DESTDIR="$OUTPUT_DIRECTORY"
    cp -pv $BUILD_DIRECTORY/.libs/pkg-config.exe $OUTPUT_DIRECTORY/bin/
    ;;
```

Maybe that line copying pkg-config.exe should only be run if $BUILD_OS is win32? I'm sure @evangreen can answer us.

**Comment by melezhik** [comment]
> Maybe that line copying pkg-config.exe should only be run if $BUILD_OS is win32? I'm sure @evangreen can answer us.

This thought was in mind, but I hung back to say it here ... Anyway building *.exe file for linux environment looks suspicious imho ...

**Comment by evangreen** [comment]
Whoops, yes that copy should have only applied to Windows builds. I've pushed change `f0485460325113d04218b4ff0c889cefd1a75da4` to the third-party repository. I haven't actually tested pkg-config on a Linux build. Can you verify that it works? Dies the irssi package build after you've built pkg-config with make-tools?

**Comment by melezhik** [comment]
> Dies the irssi package build after you've built pkg-config with make-tools?

I still have troubles with building irssi on my linuxes ( both debian/ubuntu ), but to be consistent I decided first of all to solve this issue ...

**Comment by vascocosta** [comment]
@evangreen 

This was building flawlessly on Windows but not on Linux. So I just changed the CFLAGS and it stopped complaining about the location of glib.h and glibconfig.h. After this change I've successfully built it on Linux.

Here's the merge request fixing the issue: https://gitlab.com/minoca/third-party/merge_requests/6

**Comment by melezhik** [comment]
Yes, you are right @vascocosta , missing glib.h , glibconfig.h was another issues I was running into when building irssi , but as I told I decided not to put all the things here at once...

**Comment by melezhik** [comment]
Hi @evangreen  targets: pkg-config-0.29.1,pkg-config-0.29.1-tools succeeded after getting your commit:

```
melezhik@melezhik-pc:~/minoca/third-party/build/pkg-config-0.29.1$ git log . | head
commit f0485460325113d04218b4ff0c889cefd1a75da4
Author: Evan Green <evan@minocacorp.com>
Date:   Mon Nov 28 10:16:56 2016 -0800

    Restrict pkg-config.exe copy to win32.
    
    Building pkg-config as a tool broke non-Windows builds, because
    pkg-config.exe is only built on Windows. Hopefully the other OSes don't
    need the explicit copy.

```

**Comment by melezhik** [comment]
@vascocosta , @evangreen  should we start  a separate issue for locations of glib.h and glibconfig.h. ? or we could use current one?

**Comment by vascocosta** [comment]
@melezhik, irssi is building correctly now on both Linux and Windows with:

```
export CFLAGS="$CFLAGS -I$DEPENDROOT/usr/include -I$DEPENDROOT/usr/include/glib-2.0 -I$DEPENDROOT/usr/lib/glib-2.0/include"
```

I submitted a merge request to the third-party repo with this change and I'm waiting it to be approved.

**Comment by melezhik** [comment]
Agree.

**Comment by evangreen** [comment]
@vascocosta I'm working through that backlog of 2 packages and that merge request now.
