### ISSUE TITLE
netcurses gets build with /usr/share/terminfo/ different from packaged one

### ISSUE THREAD

**Issue by melezhik** [minoca/os#67]
Hi!

I successfully built a libncurces and export it into minoca instance:

``` 

~# ncurses5-config --version
5.9.20110404
~# ncurses5-config --terminfo
/usr/share/terminfo
~# ls -l /usr/share/terminfo/
total 0
drwxrwxr-x  1 root root  0 Nov 28 04:10 a
drwxrwxr-x  1 root root  0 Nov 28 04:10 l
drwxrwxr-x  1 root root  0 Nov 28 04:10 p
drwxrwxr-x  1 root root  0 Nov 28 04:10 v
drwxrwxr-x  1 root root  0 Nov 28 04:10 x

```

However when I tried to run nano ( actually I guess any application depending  on libncurses ) it fails with error:

```
~# echo $TERM
xterm
~# nano
Error opening terminal: xterm.

```

Debugging this issue for wahile I found a terminfo discrepancy  between one gets compiled libncurses - `/usr/share/terminfo/` and exported to my instance and those one shipped via libncurses package through www.minocacorp.com/packages/ repository - `http://www.minocacorp.com/packages/0.3/i686/main/libncurses_5.9_minoca-i686.ipk` . 

What is interesting, coping a terminfo from downloaded libncurses package into my /usr/share/termininfo fixes my issue:

bash-4.3# wget http://www.minocacorp.com/packages/0.3/i686/main/libncurses_5.9_minoca-i686.ipk
--2016-11-28 05:00:01--  http://www.minocacorp.com/packages/0.3/i686/main/libncurses_5.9_minoca-i686.ipk
Resolving www.minocacorp.com... 107.170.240.123
Connecting to www.minocacorp.com|107.170.240.123|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1330196 (1.3M) [application/octet-stream]
Saving to: ‘libncurses_5.9_minoca-i686.ipk’

100%[=================================================================================>] 1,330,196    662KB/s   in 2.0s   

2016-11-28 05:00:04 (662 KB/s) - ‘libncurses_5.9_minoca-i686.ipk’ saved [1330196/1330196]

bash-4.3# ar x libncurses_5.9_minoca-i686.ipk 
bash-4.3# tar -xzf data.tar.gz 
bash-4.3# ls -l
total 5224
-rw-r--r--  1 root root      346 Nov 28 05:00 control.tar.gz
-rw-r--r--  1 root root  1329657 Nov 28 05:00 data.tar.gz
-rw-r--r--  1 root root        4 Nov 28 05:00 debian-binary
-rw-r--r--  1 root root  1330196 Nov 07 22:56 libncurses_5.9_minoca-i686.ipk
drwxr-xr-x  1 root root     4096 Nov 07 18:31 usr
bash-4.3# ls -l  ./usr/share/terminfo/
total 40
drwxr-xr-x  1 root root  4096 Nov 07 18:31 61
drwxr-xr-x  1 root root  4096 Nov 07 18:31 6c
drwxr-xr-x  1 root root  4096 Nov 07 18:31 70
drwxr-xr-x  1 root root  4096 Nov 07 18:31 76
drwxr-xr-x  1 root root  4096 Nov 07 18:31 78

cp -r ./usr/share/terminfo/* /usr/share/terminfo/

bash-4.3# ls -l /usr/share/terminfo/                       
total 40
drwxr-xr-x  1 root root  4096 Nov 28 05:01 61
drwxr-xr-x  1 root root  4096 Nov 28 05:01 6c
drwxr-xr-x  1 root root  4096 Nov 28 05:01 70
drwxr-xr-x  1 root root  4096 Nov 28 05:01 76
drwxr-xr-x  1 root root  4096 Nov 28 05:01 78
drwxrwxr-x  1 root root     0 Nov 28 04:10 a
drwxrwxr-x  1 root root     0 Nov 28 04:10 l
drwxrwxr-x  1 root root     0 Nov 28 04:10 p
drwxrwxr-x  1 root root     0 Nov 28 04:10 v
drwxrwxr-x  1 root root     0 Nov 28 04:10 x
```
```

So the question if terminfo discrepancy expectable ?

**Comment by evangreen** [comment]
Hi Alexey,
How did you build ncurses when you built your own? Did you run 'make' inside third-party/build/ncurses-5.9? The way it is supposed to work is that line 46 of build.sh (`export cf_cv_mixedcase=no`) forces ncurses to index its /usr/share/terminfo by hex number, rather than mixed-case letter. We did this so that we could build ncurses for Minoca on a Windows machine, which does not support mixed cases (meaning you cannot have directory ABC and AbC, to Windows they are the same).

Line 100 of build.sh (`tic -x -s ...`) is the part where we build the share/terminfo information. Is it possible that the `tic` being used is a system tic rather than the tic built as part of Minoca tools? Use `which tic` or `type tic` to find out where tic is coming from.

We recommend that you have the Minoca tools first in your PATH, if it is not already.

**Comment by melezhik** [comment]
Hi Evan! I will take a look and try to repeat my steps taking into account the information you told here ...

**Comment by melezhik** [comment]
Hi Evan! You were right. Rebuilding with Minoca tools first in the  PATH resulted in right terminfo this time:

```
melezhik@melezhik-pc:~/projects/minoca-build$ ls -l ~/minoca/x86dbg/bin/apps/usr/share/terminfo/
total 20
drwxrwxr-x 2 melezhik melezhik 4096 нояб. 29 13:59 61
drwxrwxr-x 2 melezhik melezhik 4096 нояб. 29 13:59 6c
drwxrwxr-x 2 melezhik melezhik 4096 нояб. 29 13:59 70
drwxrwxr-x 2 melezhik melezhik 4096 нояб. 29 13:59 76
drwxrwxr-x 2 melezhik melezhik 4096 нояб. 29 13:59 78

``` 

And then nano successfully started at running minoca instance ...
