### ISSUE TITLE
fail to build glib on ubuntu

### ISSUE THREAD

**Issue by melezhik** [minoca/os#69]
Hi!

Here is all the details - https://gist.github.com/melezhik/3ca5c53d2274cc188f5c0fb6163f76d8#gistcomment-1934291

In short I am trying to `make glib-2.49.6` and end up with error: `collect2: error: ld returned 1 exit status` 
a previous lines might be helpful : 

```
/home/melezhik/minoca/src/x86dbg/tools/bin/../lib/gcc/i686-pc-minoca/4.9.2/../../../../i686-pc-minoca/bin/ld: warning: libgcc_s.so.1, needed by ./.libs/libglib-2.0.so, not found (try using -rpath or -rpath-link)
```

I am on Ubuntu:

```

$ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l



```

**Comment by vascocosta** [comment]
I remember having this same issue when building on Ubuntu before. I don't remember exactly how I fixed it but I'll try to reproduce this on my end and comment further.

@evangreen Feel free to leave this one to me, if you don't have the time to reproduce it.

**Comment by evangreen** [comment]
It sounds like glib has a dependency on libgcc that's not explicitly called out. Alexey, can you take a look at third-party/build/sqlite-autoconf-3080500/build.sh for an example? The two lines you'll need to add are `LIBGCC=libgcc_4.9.2` and the `extract_dependency "$LIBGCC ..."` on lines 23 and 44 of sqlite's build.sh respectively. The complete fix also needs a libgcc dependency in glib's package.sh too. 

If that doesn't do it, then I will need Vasco's help. Vasco, if that does work, do you have time to draft a pull request for it?

**Comment by vascocosta** [comment]
That fixed it @evangreen.

I'm drafting a pull request for this one as I type.

**Comment by vascocosta** [comment]
Pull request submitted.

I didn't need to change package.sh because the manifest already included the libgcc dependency.

**Comment by melezhik** [comment]
HI Evan and Gluon. Looks like the [patch](https://gitlab.com/minoca/third-party/merge_requests/7) did the trick, glib now gets compiled, thanks!
