### ISSUE TITLE
Time is set to uninitialized value on Raspberry Pi

### ISSUE THREAD

**Issue by evangreen** [minoca/os#78]
The Raspberry Pi UEFI implementation is returning EFI_SUCCESS for the get/set time related functions despite not doing anything. This results in GetTime returning an uninitialized wild value.

These time-related functions should fail, and then we need to make sure in the kernel that whatever status code is returned is properly translated to STATUS_NO_SUCH_DEVICE so it can be swallowed by KeSetSystemTime.

The following functions have issues:
EfipBcm2835GetTime
EfipBcm2835SetTime
EfipBcm2835GetWakeupTime
EfipBcm2835SetWakeupTime
EfipBcm2836GetTime
EfipBcm2836SetTime
EfipBcm2836GetWakeupTime
EfipBcm2836SetWakeupTime

**Comment by ccstevens** [comment]
Checked in a fix for this.
