### ISSUE TITLE
swiss  "cp -p"  erroneous error:  Failed to change owner...

### ISSUE THREAD

**Issue by ryniker** [minoca/os#81]
It is proper to require elevated privilege to change the owner of a file, but "cp -p" should not
complain when the owner of a file copies it.  This is more than just a noise issue, because
cp produces an exit code of 1 instead of 0 when this happens, even though the file is copied.
The caller of cp may decide the copy failed (because of the non-zero exit code) and misbehave. 

~$ uname -a
Minoca minoca 0.3.0.1967-beta-debug ryniker-5f082d5 Nov 29 2016 17:17:20 armv6
~$ id
uid=501(ryniker) gid=501(ryniker) groups=501(ryniker)
~$ ls -l boo
-rw-r--r--  1 ryniker ryniker  4 Dec 07 17:54 boo
~$ ls -l foo
ls: Cannot stat 'foo': No such file or directory.
~$ ls -ld .
drwxr-sr-x  1 ryniker ryniker  4096 Dec 07 17:56 .
~$ cp -p boo foo
cp: Failed to change owner of 'foo': Operation not permitted.
~$ echo $?
1
~$ ls -l foo
-rw-r--r--  1 ryniker ryniker  4 Dec 07 17:54 foo
~$

**Comment by evangreen** [comment]
I've pushed change 62534762f6e735a62a1aae6997bb6d21ab653ce0 to address this.

**Comment by evangreen** [comment]
I'm going to go ahead and close this because the fix is pretty simple. If you do get around to verifying and it turns out not to work, feel free to re-open.
