### ISSUE TITLE
wcstok in /usr/include/wchar.h  POSIX issue

### ISSUE THREAD

**Issue by ryniker** [minoca/os#84]
Minoca defines wcstok to use 2 arguments, but ISO/IEC 9899 (reference
http://www.open-std.org/JTC1/SC22/wg14/www/docs/n1124.pdf) specifies 3 arguments
in section "7.24.4.5.7 The wcstok function".

This causes a problem for Python 3.5.2, and presumably other programs that wish to use
this part of the C library.

Is there any reason Minoca should not be up to date in this matter?

**Comment by ryniker** [comment]
Minoca has the three-argument wcstok library function, but calls it wcstok_r.   There may be
a story here.  Source is in minoca/os/apps/libc/dynamic/wstring.c with the comment
(for wcstok) "This routine is neither thread safe nor reentrant." which is certainly true.
Is there any reason not to change to the modern (2005) standard?

**Comment by evangreen** [comment]
This looks like just a bad copy/paste job from the non-wide versions, strtok and strtok_r. wcstok_r should be renamed wcstok, and the original wcstok should be removed.

**Comment by evangreen** [comment]
I've pushed change 0ad5d6c0bf6b9793da5415ed26120ab6cab33352 to fix this up.
