### ISSUE TITLE
Consider setting a default root password in install-minimal

### ISSUE THREAD

**Issue by vascocosta** [minoca/os#85]
Since "install-minimal" goes as far as installing dropbear, presumably to allow remote access out of the box, should we consider setting a default root password, so that we can ssh into a headless machine right away?

This thought crossed my mind as I had to plug a keyboard into an RPI3 which has no input/output devices connected to it, just to blindly set the password for root and subsequently be able to access it remotely using ssh.

**Comment by melezhik** [comment]
Hi @vascocosta ,  +1 for this , probably it is even better to set empty root password ? Passwd -d.

**Comment by vascocosta** [comment]
Or maybe for security reasons ask the user to interactively provide one or generate a random string?

**Comment by evangreen** [comment]
The root password is already empty, it's just most SSH servers won't allow you to log in as root if the root password is empty. I don't really love default passwords, as they provide the illusion of security and never end up getting changed. The install-minimal script tries to help set up a public/private keypair for you to use (and you can always add your own manually). Is there a reason that login by keypair doesn't work for you guys?

**Comment by vascocosta** [comment]
Oh, I totally missed the script was creating a keypair. It works for me.

**Comment by melezhik** [comment]
Hi @evangreen keypair is fine.
