### ISSUE TITLE
Dropbear's scp looks for dbclient in /usr/bin/ instead of /usr/sbin/

### ISSUE THREAD

**Issue by vascocosta** [minoca/os#87]
```
~# scp -P23722 root@185.164.138.18:/root/kernel .
/usr/bin/dbclient: No such file or directory
~# ln -s /usr/sbin/dbclient /usr/bin/
~# scp -P23722 root@185.164.138.18:/root/kernel .

Host '185.164.138.18' is not in the trusted hosts file.
(ecdsa-sha2-nistp256 fingerprint md5 06:6e:5f:50:73:4b:32:e7:7b:6d:cb:0d:9e:a4:94:0f)
Do you want to continue connecting? (y/n) y
```

A simple symbolic link fixes this issue.

**Comment by evangreen** [comment]
I pushed a change to third-party that moves these paths around. I think dropbear is right, dbclient should be in /usr/bin, not /usr/sbin. If you're able to pull in the latest to third-party and rebuild dropbear, the executables should now be in the right place.

**Comment by vascocosta** [comment]
Your change fixed this issue and I agree with you about dropbear being right.
