### ISSUE TITLE
can't make minoca os - chpasswd.c:505:39: error: ‘Status’ ... 

### ISSUE THREAD

**Issue by melezhik** [minoca/os#89]
here is details - https://gist.github.com/melezhik/316833bf8c74f182a100a0820a9bbaaa

PS I am on linux / ubuntu

**Comment by evangreen** [comment]
Hi Alexey. I pushed change 613398b5c1d9f177b596e4f63321ad94a06f1690, give it a try.

**Comment by melezhik** [comment]
HI Evan! The issue has gone after getting your change. I have tested on debian. If I get this on ubuntu I will reopen the issue.

Thanks
