### ISSUE TITLE
su hang in ssh

### ISSUE THREAD

**Issue by evangreen** [minoca/os#90]
From Richard: I can ssh to the new Minoca, login as ryniker.  If I then try "su" it stalls.  Ctrl-C is effective, but this is a bug.  I can ssh to root@minoca, enter root's password and that works.

**Comment by drawkula** [comment]
I currently have trashed all my "[PI]nocas", so I can try this only in Qemu:
```
(yeti@kumari:6)/wrk/minoca/qemu/i686$ ./run-i82559er -drive file=system-2051+2-i686.qcow2
(yeti@kumari:6)/wrk/minoca/qemu/i686$ ssh -p10686 yeti@localhost
yeti@localhost's password: 
(yeti@minoca:pty0)~$ su 
Enter password: 
/home/yeti# id
uid=0(root) gid=0(root) groups=0(root)
/home/yeti# exit
(yeti@minoca:pty0)~$ id
uid=1000(yeti) gid=1000(yeti) groups=1000(yeti),100(users)
(yeti@minoca:pty0)~$ exit
logout
Connection to localhost closed.
```
I don't remember hanging `su` with or without using `ssh`.

**Comment by evangreen** [comment]
I think this is again Richard's issue of running shells via pipes rather than pseudo-terminals. Don't know what config creates that situation.
