### ISSUE TITLE
Cygwin WARNING: Couldn't compute FAST_CWD pointer

### ISSUE THREAD

**Issue by vascocosta** [minoca/os#94]
I'm on the Insider Preview program of Windows 10, using the fast ring and after upgrading to the latest 15002.1001 build I started getting this warning when launching the Minoca development environment:

```
Minoca Build Environment for x86 (dbg).
Found ssh-agent at 220
Found ssh-agent socket at /tmp/ssh-KsKp977wVqCd/agent.7256
Cygwin WARNING:
  Couldn't compute FAST_CWD pointer.  This typically occurs if you're using
  an older Cygwin version on a newer Windows.  Please update to the latest
  available Cygwin version from https://cygwin.com/.  If the problem persists,
  please see https://cygwin.com/problems.html


Cygwin WARNING:
  Couldn't compute FAST_CWD pointer.  This typically occurs if you're using
  an older Cygwin version on a newer Windows.  Please update to the latest
  available Cygwin version from https://cygwin.com/.  If the problem persists,
  please see https://cygwin.com/problems.html

C:/Users/vasco/src/minoca#
```

**Comment by evangreen** [comment]
Hi Vasco,
This is a new one. Can you pin down exactly what binary is throwing that warning? Try removing the "echo off" from the top of /tools/win32/scripts/setenv.sh.

**Comment by vascocosta** [comment]
The culprit is git. What I usually do is download the zip version of git for Windows and then place everything under %SRCROOT%\git. This zip contains both git-cmd.exe and git-bash.exe, which is compiled against Cygwin. If I remove %SRCROOT%\git, the warning goes away. Alternatively, if I comment out the lines setting the git variables inside setenv.sh, I squelch the warning too:

```batch
rem Add git to the path if it's in src\git.
FOR %%i IN ("git.exe") DO SET GIT=%%~$PATH:i
if not exist "!GIT!" (
    if exist %SRCROOT%\git\cmd\git.exe (
        rem set GITDIR=!SRCROOT!\git
        rem set GITPATH=!GITDIR!\cmd;!GITDIR!\mingw32\bin;
        rem set PATH=!PATH!;!GITPATH!
    )

) else (
    for %%F in (!GIT!) do set GITDIR=%%~dpF\..
)
```

**Comment by evangreen** [comment]
Interesting. I notice the latest version of git available for download at https://git-scm.com/download/win is 2.11.0. Is that the version you're running? Does running with that version fix the issue?

**Comment by vascocosta** [comment]
Yeah, I upgraded to that version already but the warning is still there. Anyway, this is not a Minoca issue, so I'll try to figure it out and let you know.

**Comment by evangreen** [comment]
Sounds good. Let me know if I can help.

**Comment by evangreen** [comment]
Hi Vasco. Were you able to fix this?

**Comment by vascocosta** [comment]
Hi Evan. I wasn't, but this only happens on my insider's preview machine and everything still works, despite the warning. I'm closing this issue since it's not Minoca's fault.
