### ISSUE TITLE
Makefile not updated in repository with irssi upgrade to 1.0?

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#96]
git log says:
commit fbe46ba457e5b58328337f2e7be2882d5705536d
Author:
Date:   Mon Jan 16 10:08:27 2017 -0800

    Reapply irssi diff to avoid fuzzy patches.

commit ececba9308a141bff1429479872552184dc1e1b0
Author: 
Date:   Sat Jan 7 23:10:39 2017 +0000

    Upgrade irssi to version 1.0.0

*****************
'make' in third-party says:
family@ringling:~/dlh/minocaos/minocagits/third-party$ make      
Making /home/family/dlh/minocaos/minocagits/x86dbg/obj/third-party/irssi-0.8.20.build/build.stamp
make[1]: *** build/irssi-0.8.20: No such file or directory.  Stop.
Makefile:272: recipe for target '/home/family/dlh/minocaos/minocagits/x86dbg/obj/third-party/irssi-0.8.20.build/build.stamp' failed
make: *** [/home/family/dlh/minocaos/minocagits/x86dbg/obj/third-party/irssi-0.8.20.build/build.stamp] Error 2

**Comment by d-hoke** [comment]
In third-party/Makefile, changing irssi-0.8.20  to irssi-1.0.0 allows make to proceed without that error.

**Comment by vascocosta** [comment]
Hi @d-hoke,

Thanks a lot for spotting this one. I just fixed it and opened a merge request at:

https://gitlab.com/minoca/third-party/merge_requests/10

Once @evangreen sees this thread he should pull it in.

PS:

@d-hoke on a different note, I'd like to ask you, if possible, if you could edit your initial post on this thread and remove my email next to "Author: Vasco Costa". This is just to prevent any web crawler from harvesting it and send me SPAM. Thank you so much. :)

**Comment by d-hoke** [comment]
Sorry about overlooking the email.  Unfortunately, I don't seem to be able to figure out how to delete it, maybe someone with more privileges can... I'll keep trying to figure out what I'm overlooking, so maybe it will disappear...

**Comment by d-hoke** [comment]
Ok, figured it out - should be gone now.  again, sorry.

**Comment by vascocosta** [comment]
No problem at all. Thanks.

**Comment by evangreen** [comment]
Pushed a fix for this.
