### ISSUE TITLE
repository item third-party/src/nasm-2.12.02.tar.gz not in gzip format

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#97]
tar -ztvf nasm-2.12.02.tar.gz reports
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

but 
tar -tvf nasm-2.12.02.tar.gz gives a listing of the files in the archive.

**Comment by d-hoke** [comment]
cd src
mv nasm-2.12.02.tar.gz nasm-2.12.02.tar
gzip nasm-2.12.02.tar
cd ..
make
allows build to continue past this.

**Comment by vascocosta** [comment]
Nice work again spotting this one too @d-hoke. I fixed it and submitted a merge request here:

https://gitlab.com/minoca/third-party/merge_requests/11

Once @evangreen sees this he should pull in the fix.

**Comment by d-hoke** [comment]
Build was failing because of the item was not in gzip expected by the build process.

**Comment by ccstevens** [comment]
Evan actually already caught this and pushed a fix to our local branches.

On Jan 21, 2017, at 15:29, Vasco Costa <notifications@github.com <mailto:notifications@github.com> > wrote:

Nice work again spotting this one too @d-hoke. I fixed it and submitted a merge request here:

https://gitlab.com/minoca/third-party/merge_requests/11

Once @evangreen sees this he should pull in the fix.

**Comment by vascocosta** [comment]
Ah, thanks for the heads up Chris.

**Comment by evangreen** [comment]
I'll push out to github/gitlab soon. I just need to get a couple small additional fixes in. Should be sometime today.

**Comment by evangreen** [comment]
This should be fixed. Give it a go.
